Vagrant.configure("2") do |c|
    c.vm.box = "bento/ubuntu-16.04"
    c.vm.hostname = "honest-mistake"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    c.vm.network "public_network", type: "dhcp", :bridge => 'wlp3s0f0'

    c.vm.provider :virtualbox do |vb|
        vb.customize [
            'modifyvm', :id,
            '--natdnshostresolver1', 'on',
            '--memory', '2048',
            '--cpus', '2'
         ]
  end
end
